version: '3.6'

services:
  bothub-webapp:
    image: ${BOTHUB_WEBAPP_DOCKER_IMAGE_NAME:-bothubit/bothub-webapp}:${BOTHUB_WEBAPP_DOCKER_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      environment:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
        - VITE_BOTHUB_NLP_BASE_URL=${VITE_BOTHUB_NLP_BASE_URL:-http://localhost:2657/}
        - VITE_BOTHUB_WEBAPP_BASE_URL=${VITE_BOTHUB_WEBAPP_BASE_URL:-http://localhost:8080/}
        - VITE_SUPPORTED_LANGUAGES=${VITE_SUPPORTED_LANGUAGES:-en|pt_br}
        - VITE_MAILCHIMP_LOGIN=${VITE_MAILCHIMP_LOGIN}
        - VITE_MAILCHIMP_DATACENTER=${VITE_MAILCHIMP_DATACENTER}
        - VITE_MAILCHIMP_USER_ID=${VITE_MAILCHIMP_USER_ID}
        - VITE_MAILCHIMP_LIST_ID=${VITE_MAILCHIMP_LIST_ID}
    ports:
      - 80:80
